name: 'Chkk Kubernetes Manifestd Directory'
description: 'Check your Kubernetes manifests inside a directory for reliability risks'
inputs:
  helm-chart-path:
    description: 'Path to Helm Chart'
    required: true
  helm-version:
    description: 'Helm version used'
    required: true
    default: "v3"
  helm-parameters:
    description: 'Additional Helm parameters'
    required: false
  skip-checks:
    description: 'List of checks to skip'
    required: false
    default: "default"
  run-checks:
    description: 'List of checks to run'
    required: false
    default: "default"
  args:
    description: 'Additional arguments to pass to Chkk'
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        if [[ "$helm_version" = "v3" ]]; then
          echo "Using helm v3";
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3;
          chmod 700 get_helm.sh;
          ./get_helm.sh;
        elif [[ "$helm_version" = "v2" ]]; then
          echo "Using helm v2";
          curl -sSL https://get.helm.sh/helm-v2.16.6-linux-amd64.tar.gz | tar zx;
          sudo cp linux-amd64/helm /usr/local/bin/helm;
        fi;
      shell: bash
    - run: curl -Lo chkk https://downloads.chkk.dev/v0.0.1/chkk-linux-amd64
      shell: bash
    - run: chmod +x chkk
      shell: bash
    - run: helm template ${{helm-chart-path}} ${{helm-parameters}} | ${{ github.workspace }}/chkk -f - -r ${{ inputs.run-checks }} -s ${{ inputs.skip-checks }} ${{ inputs.args }}
      shell: bash
